resolver: lts-5.16

packages:
- location: '.'
- location:
    git:    https://github.com/neovimhaskell/nvim-hs
    commit: ef776a9b2d99042bd35495ca1d17f1a35507a1dc
extra-deps:
- dates-0.2.2.1
flags: {}
extra-package-dbs: []
